apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-payment
  namespace: test
spec:
  params:
    - name: namespace

  workspaces:
  - name: source

  steps:
    - name: deploy
      workingDir: $(workspaces.source.path)/tekton-files/svc-deployments
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "payment-dep.yml"
        - "-f"
        - "payment-svc.yml"
        - "-n"
        - "$(params.namespace)"
