apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: source
  steps:
    - name: e2e-test
      image: bhanbashi/e2e-test
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/e2e/runner.sh"
