apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
  namespace: test
spec:
  steps:
    - name: e2e-test
      image: "ozb96/e2e-test"
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/app/runner.sh"
