apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: wait-pods-start
  namespace: tekton-pipelines
spec:
  params:
    - name: namespace
    - name: serivceName
      description: the name of the serivce

  steps:
    - name: wait-for-other-pods
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "wait"
        - "--namespace"
        - "$(params.namespace)"
        - "--for=condition=ready"
        - "pods"
        - "-l"
        - "name=$(params.serivceName)"
        - "--timeout=900s"
