apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-js-test-pipeline
  namespace: test
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: image

  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/BHanbashi/level3-project
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"

  - name: build-e2e-js-test
    taskRef:
      name: build-e2e-js-test
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.image)
    - name: EXTRA_ARGS
      value: "--skip-tls-verify"

  - name: verify-digest
    runAfter:
    - build-e2e-js-test
    params:
    - name: digest
      value: $(tasks.build-e2e-js-test.results.IMAGE-DIGEST)
    taskSpec:
      params:
      - name: digest
      steps:
      - name: bash
        image: ubuntu
        script: |
          echo $(params.digest)
          case .$(params.digest) in
            ".sha"*) exit 0 ;;
            *)       echo "Digest value is not correct" && exit 1 ;;
          esac

  - name: deploy-to-test
    taskRef:
      name: deploy-e2e-js-test
    runAfter:
    - verify-digest
    workspaces:
    - name: source
      workspace: shared-workspace
    params: 
    - name: namespace
      value: "test"

#  unit-test

  - name: deploy-to-production
    taskRef:
      name: deploy-e2e-js-test
    runAfter:
    - deploy-to-test
    workspaces:
    - name: source
      workspace: shared-workspace
    params: 
    - name: namespace
      value: "production"
