apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-orders-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: admin
  pipelineRef:
    name: orders-pipeline
  params:
  - name: image
    value: bhanbashi/orders
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: orders-pvc
