apiVersion: v1
kind: Service
metadata:
  name: e2e-js-test
  labels:
    app: e2e-js-test
  annotations:
    prometheus.io/path: "/prometheus"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: e2e-js-test
