apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-queue-master-pipeline
  namespace: test
spec:
  serviceAccountName: admin
  pipelineRef:
    name: queue-master-pipeline
  params:
  - name: image
    value: bhanbashi/queue-master
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: queue-master-pvc
