apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-catalogue-pipeline
  namespace: test
spec:
  serviceAccountName: admin
  pipelineRef:
    name: catalogue-pipeline
  params:
  - name: db-image
    value: bhanbashi/catalogue-db
  - name: image
    value: bhanbashi/catalogue
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: catalogue-pvc
