apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-frontend-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: admin
  pipelineRef:
    name: frontend-pipeline
  params:
  - name: image
    value: bhanbashi/front-end
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: frontend-pvc

