apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-payment-pipeline
  namespace: tekton-pipelines
spec:
  serviceAccountName: admin
  pipelineRef:
    name: payment-pipeline
  params:
  - name: image
    value: bhanbashi/payment
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: payment-pvc
