apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: run-user-pipeline
  namespace: test
spec:
  serviceAccountName: admin
  pipelineRef:
    name: user-pipeline
  params:
  - name: db-image
    value: bhanbashi/user-db
  - name: image
    value: bhanbashi/user
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: user-pvc
